# Generated by Django 4.2.7 on 2025-10-14 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        # Rename the table from user_profiles to user_auth_userprofile
        migrations.RunSQL(
            "ALTER TABLE user_profiles RENAME TO user_auth_userprofile;",
            reverse_sql="ALTER TABLE user_auth_userprofile RENAME TO user_profiles;",
        ),
    ]
