# Generated by Django 4.2.7 on 2025-10-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0002_auto_20251014_0054"),
    ]

    operations = [
        # Rename the table from user_auth_userprofile to users_profiles
        migrations.RunSQL(
            "ALTER TABLE user_auth_userprofile RENAME TO users_profiles;",
            reverse_sql="ALTER TABLE users_profiles RENAME TO user_auth_userprofile;",
        ),
    ]
