# Generated by Django 4.2.7 on 2025-10-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_auto_20251014_0106"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="users_profiles",
        ),
    ]
