# Generated by Django 4.2.7 on 2025-10-14 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0004_alter_userprofile_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="userprofile",
            table="user_profiles",
        ),
    ]
