# Generated by Django 4.2.7 on 2025-09-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('example', '0001_initial'), ('example', '0002_clubs_club_type'), ('example', '0003_alter_clubs_club_type'), ('example', '0004_alter_clubs_club_type')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100, unique=True)),
                ('categories', models.CharField(max_length=255)),
                ('club_page', models.URLField(blank=True, null=True)),
                ('ig', models.URLField(blank=True, null=True)),
                ('discord', models.URLField(blank=True, null=True)),
                ('club_type', models.CharField(blank=True, choices=[('WUSA', 'WUSA'), ('Athletics', 'Athletics'), ('Student Society', 'Student Society')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
    ]
