# Generated by Django 4.2.7 on 2025-09-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_squashed_0004_alter_clubs_club_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="drinks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="food",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="registration",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="events",
            name="snacks",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
