# Generated by Django 4.2.7 on 2025-09-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_squashed_0004_alter_clubs_club_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
