# Generated by Django 4.2.7 on 2025-09-12 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_events_drinks_events_food_events_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='drinks',
        ),
        migrations.RemoveField(
            model_name='events',
            name='snacks',
        ),
    ]
