# Generated by Django 4.2.7 on 2025-09-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0005_events_image_url"),
        ("example", "0006_remove_events_drinks_remove_events_snacks"),
    ]

    operations = []
