# Generated by Django 4.2.7 on 2025-10-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0002_auto_20251013_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettersubscriber",
            name="email_encrypted",
            field=models.TextField(
                blank=True,
                help_text="AES encrypted email address",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="newslettersubscriber",
            name="email_hash",
            field=models.CharField(
                help_text="SHA-256 hash of the email for lookup",
                max_length=128,
                unique=True,
            ),
        ),
    ]
